enabled: true

nameOverride: ""
fullnameOverride: ""

clusterName: "quizzer-mongodb"
crVersion: "1.22.0"

image:
  repository: "percona/percona-server-mongodb"
  tag: "8.0.19-7"
  pullPolicy: IfNotPresent

replsets:
  - name: "rs0"
    size: 1
    storage:
      className: "local-path"
      size: "5Gi"

secrets:
  users: ""

users: []