{{- if and (not .Values.appSecret.existingSecretName) .Values.appSecret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "api-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.appSecret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}