<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Confluent.Kafka" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
      <PackageReference Include="Serilog" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Messaging.Contracts\Messaging.Contracts.csproj" />
      <ProjectReference Include="..\Application\Application.csproj" />
      <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

</Project>
